import json
'''This script outputs the relative position (left or right )of the person labelled 1 (woman) with respect to the other
 participant for key frames for different points of view. The camera order is 4.2 6.0 6.1 6.3 G2
 Note : If only person 1 is visible on the image, the annotation should be 'left' as the other detection will be put at
 infinity. Similarly, if person 1 is not visible, the annotation should be 'right'.'''
dict = {}

dict["frame_0"] = ['left', 'right', 'right', 'right', 'left']
dict["frame_50"] = ['right', '', '', '', '']
dict["frame_1000"] = ['left', '', '', '', '']
dict["frame_1313"] = ['left', '', '', '', '']
dict["frame_1969"] = ['left', '', '', '', '']
dict["frame_2477"] = ['left', '', '', '', '']
dict["frame_2933"] = ['left', '', '', '', '']
dict["frame_3640"] = ['left', '', '', '', '']
dict["frame_3840"] = ['left', '', '', '', '']
dict["frame_4033"] = ['left', '', '', '', '']
dict["frame_5933"] = ['left', '', '', '', '']
dict["frame_6055"] = ['left', '', '', '', '']
dict["frame_6179"] = ['right', '', '', '', '']
dict["frame_6319"] = ['left', '', '', '', '']
dict["frame_6858"] = ['right', '', '', '', '']
dict["frame_7029"] = ['left', '', '', '', '']
dict["frame_8906"] = ['left', '', '', '', '']
dict["frame_9127"] = ['left', '', '', '', '']
dict["frame_9484"] = ['left', '', '', '', '']

dict["frame_325"] = ['', 'left', '', '', '']
dict["frame_327"] = ['', 'left', '', '', '']
dict["frame_721"] = ['', 'left', '', '', '']
dict["frame_1033"] = ['', 'left', '', '', '']
dict["frame_2575"] = ['', 'right', '', '', '']
dict["frame_2985"] = ['', 'left', '', '', '']
dict["frame_3316"] = ['', 'right', '', '', '']
dict["frame_4238"] = ['', 'right', '', '', '']
dict["frame_4356"] = ['', 'left', '', '', '']
dict["frame_4937"] = ['', 'right', '', '', '']
dict["frame_5711"] = ['', 'left', '', '', '']
dict["frame_7414"] = ['', 'right', '', '', '']
dict["frame_7531"] = ['', 'left', '', '', '']
dict["frame_8942"] = ['', 'left', '', '', '']
dict["frame_9380"] = ['', 'left', '', '', '']
dict["frame_9406"] = ['', 'left', '', '', '']

dict["frame_1014"] = ['', '', 'left', '', '']
dict["frame_2369"] = ['', '', 'left', '', '']
dict["frame_2569"] = ['', '', 'left', '', '']
dict["frame_2584"] = ['', '', 'right', '', '']
dict["frame_4056"] = ['', '', 'left', '', '']
dict["frame_5085"] = ['', '', 'right', '', '']
dict["frame_5409"] = ['', '', 'left', '', '']
dict["frame_5542"] = ['', '', 'left', '', '']
dict["frame_5947"] = ['', '', 'left', '', '']
dict["frame_5949"] = ['', '', 'left', '', '']
dict["frame_6134"] = ['', '', 'left', '', '']
dict["frame_7274"] = ['', '', 'left', '', '']
dict["frame_7910"] = ['', '', 'right', '', '']
dict["frame_8534"] = ['', '', 'left', '', '']
dict["frame_9791"] = ['', '', 'left', '', '']

dict["frame_333"] = ['', '', '', 'left', '']
dict["frame_730"] = ['', '', '', 'left', '']
dict["frame_928"] = ['', '', '', 'left', '']
dict["frame_1208"] = ['', '', '', 'left', '']
dict["frame_1610"] = ['', '', '', 'left', '']
dict["frame_1668"] = ['', '', '', 'left', '']
dict["frame_1864"] = ['', '', '', 'left', '']
dict["frame_2068"] = ['', '', '', 'left', '']
dict["frame_3501"] = ['', '', '', 'left', '']
dict["frame_4372"] = ['', '', '', 'left', '']
dict["frame_4647"] = ['', '', '', 'left', '']
dict["frame_4894"] = ['', '', '', 'right', '']
dict["frame_5974"] = ['', '', '', 'left', '']
dict["frame_7157"] = ['', '', '', 'left', '']
dict["frame_7288"] = ['', '', '', 'left', '']
dict["frame_7383"] = ['', '', '', 'right', '']
dict["frame_7811"] = ['', '', '', 'left', '']
dict["frame_7836"] = ['', '', '', 'left', '']
dict["frame_7848"] = ['', '', '', 'right', '']
dict["frame_9827"] = ['', '', '', 'left', '']
dict["frame_9830"] = ['', '', '', 'left', '']
dict["frame_9981"] = ['', '', '', 'right', '']
dict["frame_10089"] = ['', '', '', 'left', '']

dict["frame_767"] = ['', '', '', '', 'left']
dict["frame_3596"] = ['', '', '', '', 'left']
dict["frame_3812"] = ['', '', '', '', 'left']
dict["frame_4679"] = ['', '', '', '', 'left']
dict["frame_9441"] = ['', '', '', '', 'left']
dict["frame_9932"] = ['', '', '', '', 'right']

with open('anchor_dict.json', 'w') as outfile:
    json.dump(dict, outfile)