import json
'''This script outputs the relative position (left or right )of the person labelled 1 (woman) with respect to the other
 participant for key frames for different points of view. The camera order is 4. 4.2 6.0 6.1 6.2 6.3 G2
 Note : If only person 1 is visible on the image, the annotation should be 'left' as the other detection will be put at
 infinity. Similarly, if person 1 is not visible, the annotation should be 'right'.'''
dict = {}

dict["frame_0"] = ['right', 'right', 'left', 'right', 'right', 'left', 'left']
dict["frame_52"] = ['right', '', '', '', '', '', '']
dict["frame_61"] = ['left', '', '', '', '', '', '']
dict["frame_774"] = ['left', '', '', '', '', '', '']
dict["frame_1226"] = ['left', '', '', '', '', '', '']
dict["frame_1229"] = ['left', '', '', '', '', '', '']
dict["frame_1241"] = ['right', '', '', '', '', '', '']
dict["frame_2773"] = ['left', '', '', '', '', '', '']
dict["frame_6285"] = ['left', '', '', '', '', '', '']
dict["frame_6378"] = ['left', '', '', '', '', '', '']
dict["frame_6761"] = ['left', '', '', '', '', '', '']

dict["frame_763"] = ['', 'left', '', '', '', '', '']
dict["frame_3468"] = ['', 'left', '', '', '', '', '']
dict["frame_4734"] = ['', 'left', '', '', '', '', '']
dict["frame_7325"] = ['', 'left', '', '', '', '', '']

dict["frame_112"] = ['', '', 'left', '', '', '', '']
dict["frame_815"] = ['', '', 'left', '', '', '', '']
dict["frame_2808"] = ['', '', 'left', '', '', '', '']
dict["frame_3053"] = ['', '', 'left', '', '', '', '']
dict["frame_5727"] = ['', '', 'left', '', '', '', '']
dict["frame_6318"] = ['', '', 'left', '', '', '', '']
dict["frame_6454"] = ['', '', 'right', '', '', '', '']
dict["frame_6584"] = ['', '', 'left', '', '', '', '']
dict["frame_6793"] = ['', '', 'left', '', '', '', '']
dict["frame_6925"] = ['', '', 'left', '', '', '', '']
dict["frame_7028"] = ['', '', 'left', '', '', '', '']

dict["frame_602"] = ['', '', '', 'left', '', '', '']
dict["frame_798"] = ['', '', '', 'left', '', '', '']
dict["frame_3552"] = ['', '', '', 'left', '', '', '']
dict["frame_6304"] = ['', '', '', 'left', '', '', '']
dict["frame_8770"] = ['', '', '', 'left', '', '', '']
dict["frame_8772"] = ['', '', '', 'left', '', '', '']

dict["frame_2529"] = ['', '', '', '', 'left', '', '']
dict["frame_3826"] = ['', '', '', '', 'left', '', '']
dict["frame_3827"] = ['', '', '', '', 'left', '', '']
dict["frame_3841"] = ['', '', '', '', 'left', '', '']
dict["frame_3843"] = ['', '', '', '', 'right', '', '']
dict["frame_3845"] = ['', '', '', '', 'left', '', '']
dict["frame_3850"] = ['', '', '', '', 'left', '', '']
dict["frame_3936"] = ['', '', '', '', 'left', '', '']
dict["frame_3967"] = ['', '', '', '', 'left', '', '']
dict["frame_3985"] = ['', '', '', '', 'left', '', '']
dict["frame_4002"] = ['', '', '', '', 'left', '', '']
dict["frame_4051"] = ['', '', '', '', 'right', '', '']
dict["frame_4098"] = ['', '', '', '', 'right', '', '']
dict["frame_4178"] = ['', '', '', '', 'left', '', '']
dict["frame_4379"] = ['', '', '', '', 'right', '', '']
dict["frame_4391"] = ['', '', '', '', 'left', '', '']
dict["frame_4717"] = ['', '', '', '', 'left', '', '']
dict["frame_5866"] = ['', '', '', '', 'left', '', '']
dict["frame_6262"] = ['', '', '', '', 'left', '', '']
dict["frame_7898"] = ['', '', '', '', 'left', '', '']
dict["frame_8425"] = ['', '', '', '', 'right', '', '']
dict["frame_8446"] = ['', '', '', '', 'left', '', '']
dict["frame_8460"] = ['', '', '', '', 'right', '', '']

dict["frame_602"] = ['', '', '', '', '', 'left', '']
dict["frame_480"] = ['', '', '', '', '', 'right', '']
dict["frame_824"] = ['', '', '', '', '', 'left', '']
dict["frame_1024"] = ['', '', '', '', '', 'left', '']
dict["frame_1222"] = ['', '', '', '', '', 'left', '']
dict["frame_1557"] = ['', '', '', '', '', 'left', '']
dict["frame_2702"] = ['', '', '', '', '', 'left', '']
dict["frame_2823"] = ['', '', '', '', '', 'left', '']
dict["frame_2933"] = ['', '', '', '', '', 'right', '']
dict["frame_3181"] = ['', '', '', '', '', 'left', '']
dict["frame_4998"] = ['', '', '', '', '', 'right', '']
dict["frame_5551"] = ['', '', '', '', '', 'right', '']
dict["frame_6438"] = ['', '', '', '', '', 'right', '']
dict["frame_8794"] = ['', '', '', '', '', 'left', '']

dict["frame_2042"] = ['', '', '', '', '', '', 'left']
dict["frame_2054"] = ['', '', '', '', '', '', 'left']
dict["frame_2095"] = ['', '', '', '', '', '', 'left']
dict["frame_2125"] = ['', '', '', '', '', '', 'left']
dict["frame_2204"] = ['', '', '', '', '', '', 'right']
dict["frame_2205"] = ['', '', '', '', '', '', 'right']
dict["frame_2301"] = ['', '', '', '', '', '', 'left']
dict["frame_2423"] = ['', '', '', '', '', '', 'right']
dict["frame_2427"] = ['', '', '', '', '', '', 'left']
dict["frame_3001"] = ['', '', '', '', '', '', 'right']
dict["frame_3008"] = ['', '', '', '', '', '', 'right']
dict["frame_3429"] = ['', '', '', '', '', '', 'left']
dict["frame_4691"] = ['', '', '', '', '', '', 'left']

with open('anchor_dict.json', 'w') as outfile:
    json.dump(dict, outfile)